name: Format
on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Lua source code (stylua)
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=./.stylua.toml -g *.lua -- ./src/lua

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - uses: Swatinem/rust-cache@v1
      - name: Run make rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: rustfmt

      - name: Commit formatted source files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: NeoSH Format
          default_author: github_actions
          message: "refactor: formatted code"
          push: true
